version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./outputs:/app/outputs
    command: >
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

